### ISSUE TITLE
Error while activating the maintenance mode

### ISSUE THREAD

**Issue by SiraphLP** [Fireflies/MaintenanceMode#4]
Hey,

I have a problem with your plugin. It will not be activated.
When I use the maintenance command: /mm enable, I see the following error message in the log file:

Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@512401ab, id=0, owner=me.ElieTGM.bungee.BungeePlugin@7dcf94f8, task=me.ElieTGM.bungee.EnableRunnable@3e28d9e1, delay=0, period=0, running=true) encountered an exception
java.lang.NoClassDefFoundError: org/apache/commons/lang/time/DurationFormatUtils
	at me.ElieTGM.bungee.EnableRunnable.format(EnableRunnable.java:51)
	at me.ElieTGM.bungee.EnableRunnable.run(EnableRunnable.java:27)
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang.time.DurationFormatUtils
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53)
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 6 more

I do not know why it doesn't work, I use the latest BungeeCord version and already removed all the other plugins.

I hope you can help me with this issue.

Greetings
SiraphLP

**Comment by Fireflies** [comment]
The project maintainer (@ElieTGM) has not replied since issue creation, closing the issue and marking as unresolved. Please report the incident in the discussion section [here][spigot-thread].

[spigot-thread]: https://www.spigotmc.org/resources/maintenancemode.2548/
